### PR TITLE
jenkins: kitchensink jenkinsfile

### PR DESCRIPTION
**Pull request by greut**
it fails, meaning its good :-)

https://ci.internal.exoscale.ch/blue/organizations/jenkins/zlocker/detail/zlocker/28/pipeline

### CODE REVIEW

**Comment by greut** [comment]
this needs more work.

**Comment by greut** [comment]
@brutasse now, it's better.

**Comment by greut** [comment]
thanks for the fixes!

**Comment by brutasse** [comment]
:+1:

**Pull request merged**
